id: IE6C16E35
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:04:51+00:00'
last_modified: '2022-06-08T03:22:20.837771+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22300
  title: གསང་རྙིང་རྒྱན་དང་རོལ་མོའི་བསྟན་བཅོས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9E2E:
      image_group_id: I1GS54240
      title: ''
      total_pages: 205
      order: 1
      base_file: 9E2E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
