id: P005478
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22300
  title: གསང་རྙིང་རྒྱན་དང་རོལ་མོའི་བསྟན་བཅོས
  author: ''
  volumes:
    86bcaf29de6249899c03d2dddc2e0d10:
      image_group_id: I1GS54240
      title: ''
      volume_number: 1
      total_pages: 205
      base_file: v001.txt
